{
 "title": "Ceph RGW Instance Stats",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "RGW Host",
    "query": "label_values(ceph_rgw_metadata, hostname)"
   },
   {
    "name": "instance",
    "label": "Daemon",
    "query": "label_values(ceph_rgw_metadata{hostname=~\"$host\"}, ceph_daemon)"
   },
   { "name": "cluster", "query": "label_values(cluster)" },
   {
    "name": "interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests / second (failed inverted)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_rgw_req{cluster=\"$cluster\", ceph_daemon=~\"$instance\"}[1m]) *on (ceph_daemon) group_left(hostname)(ceph_rgw_metadata{cluster='$cluster'})",
     "legendFormat": "{{ceph_daemon}}"
    },
    {
     "expr": "irate(ceph_rgw_failed_req{cluster=\"$cluster\",ceph_daemon=~\"$instance\"}[1m]) *on (ceph_daemon) group_left(hostname)(ceph_rgw_metadata{cluster='$cluster', hostname=~\"$host\"})\n",
     "legendFormat": "{{ceph_daemon}} failed"
    }
   ]
  },
  {
   "title": "Queue Active (qlen inverted)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_rgw_qlen{cluster=\"$cluster\",ceph_daemon=~\"$instance\"}[1m]) *on (ceph_daemon) group_left(hostname)(ceph_rgw_metadata{cluster='$cluster'})",
     "legendFormat": "{{ceph_daemon}} qlen"
    },
    {
     "expr": "irate(ceph_rgw_qactive{cluster=\"$cluster\",ceph_daemon=~\"$instance\"}[1m]) *on (ceph_daemon) group_left(hostname)(ceph_rgw_metadata{cluster='$cluster'})",
     "legendFormat": "{{ceph_daemon}} qactive"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_rgw_cache_hit{cluster=\"$cluster\",ceph_daemon=~\"$instance\"}[1m]) *on (ceph_daemon) group_left(hostname)(ceph_rgw_metadata{cluster='$cluster'})\n",
     "legendFormat": "{{ceph_daemon}} hit"
    },
    {
     "expr": "irate(ceph_rgw_cache_miss{cluster=\"$cluster\",ceph_daemon=~\"$instance\"}[1m]) *on (ceph_daemon) group_left(hostname)(ceph_rgw_metadata{cluster='$cluster'})\n\n",
     "legendFormat": "{{ceph_daemon}} miss"
    }
   ]
  },
  {
   "title": "Get ops / second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_rgw_get{cluster=\"$cluster\",ceph_daemon=~\"$instance\"}[1m]) *on (ceph_daemon) group_left(hostname)(ceph_rgw_metadata{cluster='$cluster'})\n",
     "legendFormat": "{{ceph_daemon}} ops"
    }
   ]
  },
  {
   "title": "Get bytes / second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_rgw_get_b{cluster=\"$cluster\",ceph_daemon=~\"$instance\"}[1m]) *on (ceph_daemon) group_left(hostname)(ceph_rgw_metadata{cluster='$cluster'})\n",
     "legendFormat": "{{ceph_daemon}} bytes"
    }
   ]
  },
  {
   "title": "Put ops / second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_rgw_put{cluster=\"$cluster\",ceph_daemon=~\"$instance\"}[1m]) *on (ceph_daemon) group_left(hostname)(ceph_rgw_metadata{cluster='$cluster'})\n",
     "legendFormat": "{{ceph_daemon}} ops"
    }
   ]
  },
  {
   "title": "Put bytes / second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_rgw_put_b{cluster=\"$cluster\",ceph_daemon=~\"$instance\"}[1m]) *on (ceph_daemon) group_left(hostname)(ceph_rgw_metadata{cluster='$cluster'})\n",
     "legendFormat": "{{ceph_daemon}} bytes"
    }
   ]
  }
 ]
}