{
 "title": "Ceph OSD DB/WAL Space",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "label_values(cluster)" },
   {
    "name": "hostname",
    "query": "label_values(ceph_osd_metadata{cluster=\"$cluster\"}, hostname)"
   },
   {
    "name": "daemon",
    "query": "label_values(ceph_osd_metadata{cluster=\"$cluster\", hostname=\"$hostname\"}, ceph_daemon)"
   },
   {
    "name": "interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Slow DB Used (by OSD)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(ceph_bluefs_slow_used_bytes{cluster=\"$cluster\", ceph_daemon=~\"$daemon\"})  *on (ceph_daemon) group_left(hostname)(ceph_osd_metadata{cluster=\"$cluster\"})",
     "legendFormat": "{{ceph_daemon}}"
    }
   ]
  },
  {
   "title": "Slow DB Used (by host)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum((ceph_bluefs_slow_used_bytes{cluster=\"$cluster\"}) *on (ceph_daemon) group_left(hostname)(ceph_osd_metadata{cluster=\"$cluster\"})) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Total DB Used (by host)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum((ceph_bluefs_db_used_bytes{cluster=\"$cluster\"}) *on (ceph_daemon) group_left(hostname)(ceph_osd_metadata{cluster=\"$cluster\"})) by (hostname)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "WAL Used (by host, often zero)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum((ceph_bluefs_wal_used_bytes{cluster=\"$cluster\"}) *on (ceph_daemon) group_left(hostname)(ceph_osd_metadata{cluster=\"$cluster\"})) by (hostname)\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}