{
 "title": "Ceph Pools",
 "time": { "from": "2018-11-14T00:30:20.912Z", "to": "2018-11-14T20:02:52.561Z" },
 "templating": {
  "list": [
   {
    "name": "pool_name",
    "query": "SHOW TAG VALUES FROM \"ceph_pg_summary_pool\" WITH KEY = \"pool_name\" "
   },
   {
    "name": "RP",
    "label": "Retention",
    "query": "SHOW RETENTION POLICIES ON collectd\t"
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput (read inverted) Bytes/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "read $tag_pool_name",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "pool_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ceph_pool_stats",
     "metrics": [
      {
       "field": "ceph_cluster_write",
       "id": "1",
       "inlineScript": "_value * 1",
       "meta": {},
       "settings": { "script": { "inline": "_value * 1" } },
       "type": "avg"
      }
     ],
     "query": "SELECT non_negative_derivative(sum(\"value\"), 1s) FROM \"$RP\".\"ceph_pool_stats\" WHERE (\"pool_name\" =~ /^$pool_name$/ AND \"type_instance\" = 'rd_bytes') AND $timeFilter GROUP BY time(10s), \"pool_name\" fill(null) offset 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "pool_name", "operator": "=~", "value": "/^$pool_name$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "rd_bytes" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "write  $tag_pool_name",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "pool_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ceph_pool_stats",
     "query": "SELECT non_negative_derivative(sum(\"value\"), 1s) FROM \"$RP\".\"ceph_pool_stats\" WHERE (\"pool_name\" =~ /^$pool_name$/ AND \"type_instance\" = 'wr_bytes') AND $timeFilter GROUP BY time(10s), \"pool_name\" fill(null) offset 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "pool_name", "operator": "=~", "value": "/^$pool_name$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "wr_bytes" }
     ]
    }
   ]
  },
  {
   "title": "Throughput Objects/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_pool_name",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ceph_pool_stats",
     "metrics": [
      {
       "field": "ceph_cluster_write",
       "id": "1",
       "inlineScript": "_value * 1",
       "meta": {},
       "settings": { "script": { "inline": "_value * 1" } },
       "type": "avg"
      }
     ],
     "query": "SELECT derivative(sum(\"value\"), 1s) FROM \"$RP\".\"ceph_pool_stats\" WHERE (\"pool_name\" =~ /^$pool_name$/ AND \"type_instance\" = 'objects') AND $timeFilter GROUP BY time(10s), \"pool_name\" fill(null) offset 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "pool_name", "operator": "=~", "value": "/^$pool_name$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "objects" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Bytes Used",
   "type": "graph",
   "description": "Number of bytes used in the test pool",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_pool_name",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "pool_name" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "ceph_pool_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pool_name", "operator": "=~", "value": "/^$pool_name$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "bytes_used" }
     ]
    }
   ]
  },
  {
   "title": "Raw Bytes Used",
   "type": "graph",
   "description": "Raw bytes used in pool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_pool_name",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "pool_name" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "ceph_pool_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pool_name", "operator": "=~", "value": "/^$pool_name$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "raw_bytes_used" }
     ]
    }
   ]
  },
  {
   "title": "Objects",
   "type": "graph",
   "description": "The number of objects in each pool",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_pool_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool_name" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "ceph_pool_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pool_name", "operator": "=~", "value": "/^$pool_name$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "objects" }
     ]
    }
   ]
  },
  {
   "title": "Objects Dirty",
   "type": "graph",
   "description": "The number of objects dirty in each pool",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_pool_name",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "pool_name" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "ceph_pool_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pool_name", "operator": "=~", "value": "/^$pool_name$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "dirty" }
     ]
    }
   ]
  }
 ]
}