{
 "title": "Ceph Cluster Summary",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "query": "label_values(cluster)" },
   {
    "name": "interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "RP",
    "query": "SHOW RETENTION POLICIES ON collectd"
   }
  ]
 },
 "panels": [
  {
   "title": "Custer Health",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_health_status{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "OSD Marked Down",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "sum by (ceph_daemon, hostname) (ceph_osd_up{cluster=\"$cluster\"}) * on (ceph_daemon) group_left (hostname)(ceph_osd_metadata{cluster=\"$cluster\"}) == 0",
     "legendFormat": "{{ceph_daemon}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "Top Sluggish OSD's",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "topk(5,sort_desc(ceph_osd_apply_latency_ms{cluster='$cluster'} + ceph_osd_commit_latency_ms{cluster='$cluster'})) * on (ceph_daemon) group_left(hostname)(ceph_osd_metadata{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Cluster Throughput (read inverted)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w_in_bytes{cluster=\"$cluster\"}[5m]))\n",
     "legendFormat": "write"
    },
    {
     "expr": "sum(irate(ceph_osd_op_r_out_bytes{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Client Ops (read inverted)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "none", "label": "ops / sec" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum(irate(ceph_osd_op_r{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Recovery/Replication ops (recovery inverted)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_recovery_ops{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "recovery (ops/s)"
    },
    {
     "expr": "sum(ceph_osd_op_wip{cluster=\"$cluster\"})",
     "legendFormat": "replication (total in process)"
    }
   ]
  },
  {
   "title": "OSD Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(ceph_osd_up{cluster=\"$cluster\"})\n",
     "legendFormat": "ALL"
    },
    {
     "expr": "sum(ceph_osd_up{cluster=\"$cluster\"} == 1)\n",
     "legendFormat": "UP"
    },
    {
     "expr": "sum(ceph_osd_in{cluster=\"$cluster\"})",
     "legendFormat": "IN"
    }
   ]
  },
  {
   "title": "Ceph Objects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceph_pool_objects{cluster=\"$cluster\"})\n",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Avg OSD  Op  Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(ceph_osd_op_r_latency_sum{cluster=\"$cluster\"}[5m]) / rate(ceph_osd_op_r_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "read"
    },
    {
     "expr": "avg(rate(ceph_osd_op_w_latency_sum{cluster=\"$cluster\"}[5m]) / rate(ceph_osd_op_w_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "AVG OSD Apply + Commit Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{cluster=\"$cluster\"})",
     "legendFormat": "apply"
    },
    {
     "expr": "avg(ceph_osd_commit_latency_ms{cluster=\"$cluster\"})",
     "legendFormat": "commit"
    }
   ]
  },
  {
   "title": "Data Pool IO (read inverted) Bytes/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_pool_rd_bytes{cluster='$cluster'}[5m]) *on (pool_id) group_left(name)(ceph_pool_metadata{cluster='$cluster'})",
     "legendFormat": "{{name}} RD"
    },
    {
     "expr": "irate(ceph_pool_wr_bytes{cluster='$cluster'}[5m]) *on (pool_id) group_left(name)(ceph_pool_metadata{cluster='$cluster'})",
     "legendFormat": "{{name}} WR"
    }
   ]
  },
  {
   "title": "Used Space (stacked)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(ceph_pool_stored{cluster='$cluster'}) *on (pool_id) group_left(name)(ceph_pool_metadata{cluster='$cluster'})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "PGs State",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceph_pg_active{cluster=\"$cluster\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "ceph_pg_clean{cluster=\"$cluster\"}",
     "legendFormat": "Clean"
    },
    {
     "expr": "ceph_pg_peering{cluster=\"$cluster\"}",
     "legendFormat": "Peering"
    },
    {
     "expr": "ceph_pg_degraded{cluster=\"$cluster\"}",
     "legendFormat": "Degraded"
    },
    {
     "expr": "ceph_pg_stale{cluster=\"$cluster\"}",
     "legendFormat": "Stale"
    },
    {
     "expr": "ceph_unclean_pgs{cluster=\"$cluster\"}",
     "legendFormat": "Unclean"
    },
    {
     "expr": "ceph_pg_undersized{cluster=\"$cluster\"}",
     "legendFormat": "Undersized"
    },
    {
     "expr": "ceph_pg_incomplete{cluster=\"$cluster\"}",
     "legendFormat": "Incomplete"
    },
    {
     "expr": "ceph_pg_forced_backfill{cluster=\"$cluster\"}",
     "legendFormat": "Forced Backfill"
    },
    {
     "expr": "ceph_pg_inconsistent{cluster=\"$cluster\"}",
     "legendFormat": "Inconsistent"
    },
    {
     "expr": "ceph_pg_forced_recovery{cluster=\"$cluster\"}",
     "legendFormat": "Forced Recovery"
    },
    {
     "expr": "ceph_pg_creating{cluster=\"$cluster\"}",
     "legendFormat": "Creating"
    },
    {
     "expr": "ceph_pg_wait_backfill{cluster=\"$cluster\"}",
     "legendFormat": "Wait Backfill"
    },
    {
     "expr": "ceph_pg_deep{cluster=\"$cluster\"}",
     "legendFormat": "Deep"
    },
    {
     "expr": "ceph_pg_scrubbing{cluster=\"$cluster\"}",
     "legendFormat": "Scrubbing"
    },
    {
     "expr": "ceph_pg_recovering{cluster=\"$cluster\"}",
     "legendFormat": "Recovering"
    },
    {
     "expr": "ceph_pg_repair{cluster=\"$cluster\"}",
     "legendFormat": "Repair"
    },
    {
     "expr": "ceph_pg_down{cluster=\"$cluster\"}",
     "legendFormat": "Down"
    },
    {
     "expr": "ceph_pg_peered{cluster=\"$cluster\"}",
     "legendFormat": "Peered"
    },
    {
     "expr": "ceph_pg_backfill{cluster=\"$cluster\"}",
     "legendFormat": "Backfill"
    },
    {
     "expr": "ceph_pg_remapped{cluster=\"$cluster\"}",
     "legendFormat": "Remapped"
    },
    {
     "expr": "ceph_pg_backfill_toofull{cluster=\"$cluster\"}",
     "legendFormat": "Backfill Toofull"
    }
   ]
  },
  {
   "title": "Alerts ",
   "type": "table",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 25 },
   "targets": [
    {
     "expr": "max by (alertname, alias, desc) (ALERTS{alertstate='firing'})",
     "legendFormat": "{{alertname}} {{alias}} {{desc}}"
    }
   ]
  }
 ]
}