{
 "title": "Ceph MDS Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "query": "label_values(cluster)" },
   {
    "name": "interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency Metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_mds_server_req_mknod_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_mknod_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "mknod_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_server_req_lookupsnap_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_lookupsnap_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "lookupsnap_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_server_req_lookupino_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_lookupino_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "lookupino_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_server_req_rmxattr_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_rmxattr_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "rmxattr_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_server_req_open_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_open_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "open_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_server_req_lookupparent_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_lookupparent_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "lookupparent_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_server_req_create_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_create_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "create_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_server_req_renamesnap_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_renamesnap_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "renamesnap_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_server_req_mkdir_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_mkdir_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "mkdir_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_server_req_setdirlayout_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_setdirlayout_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "setdirlayout_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_server_req_lssnap_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_lssnap_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "lssnap_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_server_req_setfilelock_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_setfilelock_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "setfilelock_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_server_req_setattr_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_setattr_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "setattr_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_server_req_symlink_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_symlink_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "symlink_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_server_req_readdir_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_readdir_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "readdir_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_server_req_lookup_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_lookup_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "lookup_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_server_req_unlink_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_unlink_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "unlink_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_server_req_link_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_link_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "link_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_server_req_rmsnap_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_rmsnap_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "rmsnap_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_server_req_getattr_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_getattr_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "getattr_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_server_req_rmdir_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_rmdir_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "rmdir_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_server_req_lookupname_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_lookupname_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "lookupname_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_server_req_lookuphash_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_lookuphash_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "lookuphash_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_server_req_setlayout_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_setlayout_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "setlayout_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_server_req_mksnap_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_mksnap_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "mksnap_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_server_req_getfilelock_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_getfilelock_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "getfilelock_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_server_req_rename_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_rename_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "rename_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_server_req_setxattr_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_server_req_setxattr_latency_count{cluster=\"$cluster\"}[5m]) >= 0)",
     "legendFormat": "setxattr_latency"
    },
    {
     "expr": "sum(irate(ceph_mds_reply_latency_sum{cluster=\"$cluster\"}[5m]) / irate(ceph_mds_reply_latency_count{cluster=\"$cluster\"}[5m]) >=0)",
     "legendFormat": "reply_latency"
    }
   ]
  },
  {
   "title": "MDS Requests / s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_mds_request{cluster=\"$cluster\"}[5m]))\n",
     "legendFormat": "mds_request"
    },
    {
     "expr": "sum(irate(ceph_mds_server_handle_slave_request{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "slave_request"
    },
    {
     "expr": "sum(irate(ceph_mds_server_handle_client_request{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "client_request"
    }
   ]
  },
  {
   "title": "Purge Queue Ops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ceph_purge_queue_pq_executed{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "Executed Rate"
    },
    {
     "expr": "sum(ceph_purge_queue_pq_executing{cluster=\"$cluster\"})",
     "legendFormat": "Tasks in Flight"
    },
    {
     "expr": "sum(ceph_purge_queue_pq_executing_ops{cluster=\"$cluster\"})",
     "legendFormat": "Ops in Flight"
    }
   ]
  },
  {
   "title": "MDS Cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n  {__name__=~\"ceph_mds_cache.*\"}, \"__name__\", \"$2\", \"__name__\", \"(ceph_mds_cache_)(.*)\"\n)\n",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "MDS Log Journal Flush Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ceph_mds_log_jlat_sum{cluster=\"$cluster\"}[5m]) / rate(ceph_mds_log_jlat_count{cluster=\"$cluster\"}[5m]) > 0) ",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "MDS Log",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ceph_mds_log_evadd{cluster=\"$cluster\"}[5m]))\n",
     "legendFormat": "Events Added"
    },
    {
     "expr": "sum(rate(ceph_mds_log_replayed{cluster=\"$cluster\"}[5m]))\n",
     "legendFormat": "Events Replayed"
    },
    {
     "expr": "sum(rate(ceph_mds_log_evtrm{cluster=\"$cluster\"}[5m]))\n",
     "legendFormat": "Events Trimmed"
    },
    {
     "expr": "sum(rate(ceph_mds_log_evexg{cluster=\"$cluster\"}[5m]))\n",
     "legendFormat": "Events Expiring"
    },
    {
     "expr": "sum(rate(ceph_mds_log_segadd{cluster=\"$cluster\"}[5m]))\n",
     "legendFormat": "Segments Added"
    },
    {
     "expr": "sum(rate(ceph_mds_log_segtrm{cluster=\"$cluster\"}[5m]))\n",
     "legendFormat": "Segments Trimmed"
    },
    {
     "expr": "sum(rate(ceph_mds_log_segexg{cluster=\"$cluster\"}[5m]))\n",
     "legendFormat": "Segments Expired"
    }
   ]
  }
 ]
}