{
 "title": "Ceph RGW",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Xfer Host",
    "query": "SHOW TAG VALUES FROM ceph_daemon_stats WITH KEY = \"host\" WHERE ceph_daemon =~ /.*rgw.*/\t"
   },
   {
    "name": "instance",
    "label": "RGW Instance",
    "query": "SHOW TAG VALUES FROM ceph_daemon_stats WITH KEY = \"ceph_daemon\" WHERE host =~ /$host/"
   },
   {
    "name": "RP",
    "label": "Retention Policy",
    "query": "SHOW RETENTION POLICIES ON collectd"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests / second (failed inverted)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_ceph_daemon Req",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "ceph_daemon" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ceph_daemon_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ceph_daemon", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "rgw.req" }
     ]
    },
    {
     "alias": "$tag_ceph_daemon Failed",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "ceph_daemon" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ceph_daemon_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ceph_daemon", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "rgw.failed_req" }
     ]
    }
   ]
  },
  {
   "title": "Queue Active (qlen inverted)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_ceph_daemon qlen",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "ceph_daemon" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ceph_daemon_stats",
     "query": "SELECT non_negative_derivative(mean(\"value\"), 1s) FROM \"ceph_value\" WHERE \"type_instance\" =~ /Client.*.qlen/ OR \"type_instance\" =~ /Client.*.qactive/ AND $timeFilter GROUP BY time($interval), \"host\", \"type_instance\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ceph_daemon", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "rgw.qlen" }
     ]
    },
    {
     "alias": "$tag_ceph_daemon qactive",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "ceph_daemon" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ceph_daemon_stats",
     "query": "SELECT non_negative_derivative(mean(\"value\"), 1s) FROM \"ceph_value\" WHERE \"type_instance\" =~ /Client.*.qlen/ OR \"type_instance\" =~ /Client.*.qactive/ AND $timeFilter GROUP BY time($interval), \"host\", \"type_instance\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ceph_daemon", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "rgw.qactive" }
     ]
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_ceph_daemon cache Hit / sec",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "ceph_daemon" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ceph_daemon_stats",
     "query": "SELECT non_negative_derivative(mean(\"value\"), 1s) FROM \"ceph_value\" WHERE \"type_instance\" =~ /Client.*.qlen/ OR \"type_instance\" =~ /Client.*.qactive/ AND $timeFilter GROUP BY time($interval), \"host\", \"type_instance\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ceph_daemon", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "rgw.cache_hit" }
     ]
    },
    {
     "alias": "$tag_ceph_daemon cache Miss / sec",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "ceph_daemon" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ceph_daemon_stats",
     "query": "SELECT non_negative_derivative(mean(\"value\"), 1s) FROM \"ceph_value\" WHERE \"type_instance\" =~ /Client.*.qlen/ OR \"type_instance\" =~ /Client.*.qactive/ AND $timeFilter GROUP BY time($interval), \"host\", \"type_instance\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ceph_daemon", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "rgw.cache_miss" }
     ]
    }
   ]
  },
  {
   "title": "Gets / second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_ceph_daemon Ops",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "ceph_daemon" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ceph_daemon_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ceph_daemon", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "rgw.get" }
     ]
    },
    {
     "alias": "$tag_ceph_daemon Bytes",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "ceph_daemon" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ceph_daemon_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ceph_daemon", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "rgw.get_b" }
     ]
    }
   ]
  },
  {
   "title": "Puts / second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_ceph_daemon Ops",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "ceph_daemon" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ceph_daemon_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ceph_daemon", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "rgw.put" }
     ]
    },
    {
     "alias": "$tag_ceph_daemon Bytes",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "ceph_daemon" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ceph_daemon_stats",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ceph_daemon", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "rgw.put_b" }
     ]
    }
   ]
  },
  {
   "title": "CPU % Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " - 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "idle" }
     ]
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "used" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Load Short-term",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load_shortterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}