{
 "title": "Ceph Pool Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pool_name",
    "query": "label_values(ceph_pool_metadata, name)"
   },
   { "name": "cluster", "query": "label_values(cluster)" },
   {
    "name": "interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput (read inverted) Bytes/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_pool_rd_bytes{cluster='$cluster'}[5m]) *on (pool_id) group_left(name)(ceph_pool_metadata{name=~'$pool_name',cluster='$cluster'})",
     "legendFormat": "{{name}} RD"
    },
    {
     "expr": "irate(ceph_pool_wr_bytes{cluster='$cluster'}[5m]) *on (pool_id) group_left(name)(ceph_pool_metadata{name=~'$pool_name',cluster='$cluster'})",
     "legendFormat": "{{name}} WR"
    }
   ]
  },
  {
   "title": "Total IO  (read inverted) Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(ceph_pool_rd_bytes{cluster='$cluster'}) *on (pool_id) group_left(name)(ceph_pool_metadata{name=~'$pool_name',cluster='$cluster'})",
     "legendFormat": "{{name}} RD"
    },
    {
     "expr": "(ceph_pool_wr_bytes{cluster='$cluster'}) *on (pool_id) group_left(name)(ceph_pool_metadata{name=~'$pool_name',cluster='$cluster'})",
     "legendFormat": "{{name}} WR"
    }
   ]
  },
  {
   "title": "Bytes Used",
   "type": "graph",
   "description": "Number of bytes used in the test pool",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(ceph_pool_stored{cluster='$cluster'}) *on (pool_id) group_left(name)(ceph_pool_metadata{name=~'$pool_name',cluster='$cluster'})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Throughput Objects/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(ceph_pool_objects{cluster='$cluster'}[30s]) *on (pool_id) group_left(name)(ceph_pool_metadata{name=~'$pool_name',cluster='$cluster'})\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Objects",
   "type": "graph",
   "description": "The number of objects in each pool",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(ceph_pool_objects{cluster='$cluster'}) *on (pool_id) group_left(name)(ceph_pool_metadata{name=~'$pool_name',cluster='$cluster'})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Raw Bytes Used",
   "type": "graph",
   "description": "Raw bytes used in pool",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(ceph_pool_stored_raw{cluster='$cluster'}) *on (pool_id) group_left(name)(ceph_pool_metadata{name=~'$pool_name',cluster='$cluster'})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Recovered Objects",
   "type": "graph",
   "description": "The number of objects dirty in each pool",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "objects / second" }
   ],
   "targets": [
    {
     "expr": "(ceph_pool_num_objects_recovered{cluster='$cluster'}) *on (pool_id) group_left(name)(ceph_pool_metadata{name=~'$pool_name',cluster='$cluster'})\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Recovering Objects Rate ",
   "type": "graph",
   "description": "The number of objects dirty in each pool",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s", "label": "objects / second" }
   ],
   "targets": [
    {
     "expr": "(ceph_pool_recovering_objects_per_sec{cluster='$cluster'}) *on (pool_id) group_left(name)(ceph_pool_metadata{name=~'$pool_name',cluster='$cluster'})\n",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}