{
 "title": "Ceph RGW HAproxy",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "RP",
    "label": "Retention Policy",
    "query": "SHOW RETENTION POLICIES ON collectd"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM haproxy_value WITH KEY = \"host\""
   },
   {
    "name": "instance",
    "label": "Proxy Instance",
    "query": "SHOW TAG VALUES FROM haproxy_value WITH KEY = \"instance\" "
   }
  ]
 },
 "panels": [
  { "title": "HAProxy Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Session rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_instance $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "haproxy_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "session_rate" },
      { "condition": "AND", "key": "instance", "operator": "!~", "value": "/ceph/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Throughput stacked (read inverted)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Write $tag_instance $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "haproxy_value",
     "query": "SELECT non_negative_derivative(sum(\"value\"), 1s) FROM \"$RP\".\"haproxy_value\" WHERE (\"type_instance\" = 'bytes_in' AND \"instance\" !~ /ceph-rgw/ AND \"instance\" =~ /$instance/) AND $timeFilter GROUP BY time(10s), \"instance\" fill(null) offset 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "bytes_in" },
      { "condition": "AND", "key": "instance", "operator": "!~", "value": "/ceph-rgw/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/$instance/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Read $tag_instance $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "haproxy_value",
     "query": "SELECT non_negative_derivative(sum(\"value\"), 1s) FROM \"$RP\".\"haproxy_value\" WHERE (\"type_instance\" = 'bytes_in' AND \"instance\" !~ /ceph-rgw/ AND \"instance\" =~ /$instance/) AND $timeFilter GROUP BY time(10s), \"instance\" fill(null) offset 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "bytes_out" },
      { "condition": "AND", "key": "instance", "operator": "!~", "value": "/ceph-rgw/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/$instance/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Frontend Req Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Req rate $tag_host $tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "haproxy_value",
     "query": "SELECT mean(\"value\") FROM \"$RP\".\"haproxy_value\" WHERE (\"type_instance\" = 'request_rate' AND \"instance\" =~ /ceph/ AND host=~/^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"instance\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "session_rate" },
      { "condition": "AND", "key": "instance", "operator": "!~", "value": "/ceph/" }
     ]
    }
   ]
  },
  {
   "title": "Frontend Error / s (response codes invert)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_type_instance $tag_host $tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "haproxy_value",
     "query": "SELECT non_negative_derivative(mean(\"value\"), 1s) FROM \"$RP\".\"haproxy_value\" WHERE (\"type_instance\" =~ /error|denied/ AND \"instance\" =~ /ceph/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"type_instance\", \"host\", \"instance\" offset 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=~", "value": "/error|denied/" }
     ]
    },
    {
     "alias": "client 4xx $tag_host $tag_instance",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "haproxy_value",
     "query": "SELECT non_negative_derivative(mean(\"value\"),1s) FROM \"$RP\".\"haproxy_value\" WHERE (\"type_instance\" = 'response_4xx' AND \"instance\" =~ /ceph/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\",\"instance\" offset 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "response_4xx" }
     ]
    },
    {
     "alias": "server 5xx $tag_host $tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "haproxy_value",
     "query": "SELECT non_negative_derivative(mean(\"value\"), 1s) FROM \"haproxy_value\" WHERE (\"type_instance\" = 'response_5xx' AND \"instance\" =~ /ceph/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"instance\" offset 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "response_5xx" }
     ]
    }
   ]
  },
  {
   "title": "Backend Error / s (response codes invert)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_type_instance $tag_host $tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" }
     ],
     "measurement": "haproxy_value",
     "query": "SELECT non_negative_derivative(mean(\"value\"), 1s) FROM \"$RP\".\"haproxy_value\" WHERE (\"type_instance\" =~ /error|denied/ AND \"instance\" =~ /$instance/ AND \"instance\" !~ /ceph/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"type_instance\", \"host\", \"instance\" offset 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=~", "value": "/error|denied/" }
     ]
    },
    {
     "alias": "client 4xx $tag_host $tag_instance",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "haproxy_value",
     "query": "SELECT non_negative_derivative(mean(\"value\"),1s) FROM \"$RP\".\"haproxy_value\" WHERE (\"type_instance\" = 'response_4xx' AND \"instance\" =~ /$instance/ AND \"instance\" !~ /ceph/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\",\"instance\" offset 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "response_4xx" }
     ]
    },
    {
     "alias": "server 5xx $tag_host $tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "haproxy_value",
     "query": "SELECT non_negative_derivative(mean(\"value\"), 1s) FROM \"haproxy_value\" WHERE (\"type_instance\" = 'response_5xx' AND \"instance\" =~ /$instance/ AND \"instance\" !~ /ceph/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"instance\" offset 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "response_5xx" }
     ]
    }
   ]
  },
  { "title": "System Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPU % Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " - 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "idle" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "used" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Load Short-term",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load_shortterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}