{
 "title": "Ceph Daemon Process Details",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   },
   {
    "name": "RP",
    "label": "Retention Policy",
    "query": "SHOW RETENTION POLICIES ON collectd"
   }
  ]
 },
 "panels": [
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  {
   "title": "$host CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_type_instance",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "percent" },
      { "condition": "AND", "key": "type_instance", "operator": "<>", "value": "idle" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$host Overall Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "load metrics: longterm",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load_longterm",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "load metrics: midterm",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load_midterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "load metrics: shortterm",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load_shortterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$host Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_type_instance",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type_instance", "operator": "<>", "value": "free" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "free",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "query": "SELECT sum(\"value\") FROM \"memory_value\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "free" }
     ]
    }
   ]
  },
  {
   "title": "$host ceph daemon memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_type $tag_instance",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_value",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "!~", "value": "/fork_rate|ps_state/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$host ceph daemon cpu time (invert sys)",
   "type": "graph",
   "description": "CPU time in ms derivative over 1 second.  \n1 second of CPU time used is equivalent to fully using 1 core.  Multithreaded processes may use more.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "alias": "user $tag_type $tag_instance",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_user",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "sys $tag_type $tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_syst",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$host ceph daemon Thread Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_threads",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$host ceph daemon process I/O (read inverted)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "rx $tag_instance",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_rx",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/ceph/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "tx $tag_instance",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_tx",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/ceph/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$host ceph syscall I/O (read inverted)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_instance disk write",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_write",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "$tag_instance disk read",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_read",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$host fork rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "rate / second" }
   ],
   "targets": [
    {
     "alias": "$tag_type",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_value",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "fork_rate" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$host process states",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_type $tag_type_instance",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_value",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "ps_state" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "$host CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_type_instance",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "percent" },
      { "condition": "AND", "key": "type_instance", "operator": "<>", "value": "idle" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$host Overall Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "load metrics: longterm",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load_longterm",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "load metrics: midterm",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load_midterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "load metrics: shortterm",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load_shortterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$host Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_type_instance",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type_instance", "operator": "<>", "value": "free" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "free",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "query": "SELECT sum(\"value\") FROM \"memory_value\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "free" }
     ]
    }
   ]
  },
  {
   "title": "$host ceph daemon memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_type $tag_instance",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_value",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "!~", "value": "/fork_rate|ps_state/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$host ceph daemon cpu time (invert sys)",
   "type": "graph",
   "description": "CPU time in ms derivative over 1 second.  \n1 second of CPU time used is equivalent to fully using 1 core.  Multithreaded processes may use more.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "alias": "user $tag_type $tag_instance",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_user",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "sys $tag_type $tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_syst",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$host ceph daemon Thread Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_threads",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$host ceph daemon process I/O (read inverted)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "rx $tag_instance",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_rx",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/ceph/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "tx $tag_instance",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_tx",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/ceph/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$host ceph syscall I/O (read inverted)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_instance disk write",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_write",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "$tag_instance disk read",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_read",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$host fork rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "none", "label": "rate / second" }
   ],
   "targets": [
    {
     "alias": "$tag_type",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_value",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "fork_rate" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$host process states",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_type $tag_type_instance",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_value",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "ps_state" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "$host CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_type_instance",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "percent" },
      { "condition": "AND", "key": "type_instance", "operator": "<>", "value": "idle" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$host Overall Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "load metrics: longterm",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load_longterm",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "load metrics: midterm",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load_midterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "load metrics: shortterm",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load_shortterm",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$host Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_type_instance",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type_instance", "operator": "<>", "value": "free" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "free",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "query": "SELECT sum(\"value\") FROM \"memory_value\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "free" }
     ]
    }
   ]
  },
  {
   "title": "$host ceph daemon memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_type $tag_instance",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_value",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "!~", "value": "/fork_rate|ps_state/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$host ceph daemon cpu time (invert sys)",
   "type": "graph",
   "description": "CPU time in ms derivative over 1 second.  \n1 second of CPU time used is equivalent to fully using 1 core.  Multithreaded processes may use more.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "alias": "user $tag_type $tag_instance",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_user",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "sys $tag_type $tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_syst",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "$host ceph daemon Thread Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_threads",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$host ceph daemon process I/O (read inverted)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "rx $tag_instance",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_rx",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/ceph/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "tx $tag_instance",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_tx",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/ceph/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$host ceph syscall I/O (read inverted)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_instance disk write",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_write",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "timeField": "@timestamp"
    },
    {
     "alias": "$tag_instance disk read",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_read",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$host fork rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 53 },
   "yaxes": [
    { "format": "none", "label": "rate / second" }
   ],
   "targets": [
    {
     "alias": "$tag_type",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_value",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "fork_rate" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$host process states",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_type $tag_type_instance",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes_value",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "ps_state" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}