{
 "title": "Datacenter PDU",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "PDU",
    "query": "label_values(rPDUIdentModelNumber, alias)"
   },
   {
    "name": "site",
    "query": "label_values(rPDUIdentName, site)"
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Power UM",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rPDUIdentDevicePowerWatts)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Watts",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum (rPDUIdentDevicePowerVA)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "VA",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total Power WSU",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rPDUIdentDevicePowerWatts)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Watts",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum (rPDUIdentDevicePowerVA)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "VA",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {}
     ]
    },
    {
     "title": "Total Power MSU",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rPDUIdentDevicePowerWatts)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Watts",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "sum (rPDUIdentDevicePowerVA)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "VA",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {}
     ]
    }
   ]
  },
  { "title": "$PDU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "PDU" },
  {
   "title": "Total Power $PDU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rPDUIdentDevicePowerWatts{alias='$PDU'}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "WATTS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rPDUIdentDevicePowerVA{alias='$PDU'}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "VA",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bank/Phase Load $PDU ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 2 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "rPDULoadStatusLoad{alias='$PDU',rPDULoadStatusBankNumber!='0'} / 10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Bank {{ rPDULoadStatusBankNumber }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rPDULoadStatusLoad{alias='$PDU',rPDULoadStatusBankNumber='0'} /10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Phase {{ rPDULoadStatusIndex }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Phase/Bank Status $PDU",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 2 },
   "targets": [
    {
     "expr": "max by (rPDULoadStatusBankNumber, rPDULoadStatusPhaseNumber) (rPDULoadStatusLoadState{alias='$PDU'}) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Phase/Bank {{ rPDULoadStatusIndex }} ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outlet Status $PDU",
   "type": "table",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by (alias,rPDUOutletStatusIndex) (rPDUOutletStatusOutletPhase{alias='$PDU'})  *on (alias, rPDUOutletStatusIndex) group_left (rPDUOutletStatusOutletName)(rPDUOutletStatusOutletName{alias='$PDU'})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max by (alias,rPDUOutletStatusIndex, alias) (rPDUOutletStatusOutletBank{alias='$PDU'})  *on (alias, rPDUOutletStatusIndex) group_left (rPDUOutletStatusOutletName)(rPDUOutletStatusOutletName{alias='$PDU'})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max by (alias,rPDUOutletStatusIndex) (rPDUOutletStatusLoad{alias='$PDU'})  *on (alias, rPDUOutletStatusIndex) group_left (rPDUOutletStatusOutletName)(rPDUOutletStatusOutletName{alias='$PDU'})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max by (alias,rPDUOutletStatusIndex) (rPDUOutletStatusOutletState{alias='$PDU'})  *on (alias, rPDUOutletStatusIndex) group_left (rPDUOutletStatusOutletName)(rPDUOutletStatusOutletName{alias='$PDU'})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Info $PDU",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "rPDUIdentDeviceRating{alias='$PDU'} * on (alias) group_left (rPDUIdentDateOfManufacture)(rPDUIdentDateOfManufacture{alias='$PDU'}) * on (alias) group_left (rPDUIdentModelNumber)(rPDUIdentModelNumber{alias='$PDU'})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "$PDU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total Power $PDU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rPDUIdentDevicePowerWatts{alias='$PDU'}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "WATTS",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rPDUIdentDevicePowerVA{alias='$PDU'}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "VA",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bank/Phase Load $PDU ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 14 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "rPDULoadStatusLoad{alias='$PDU',rPDULoadStatusBankNumber!='0'} / 10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Bank {{ rPDULoadStatusBankNumber }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rPDULoadStatusLoad{alias='$PDU',rPDULoadStatusBankNumber='0'} /10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Phase {{ rPDULoadStatusIndex }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Phase/Bank Status $PDU",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 14 },
   "targets": [
    {
     "expr": "max by (rPDULoadStatusBankNumber, rPDULoadStatusPhaseNumber) (rPDULoadStatusLoadState{alias='$PDU'}) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Phase/Bank {{ rPDULoadStatusIndex }} ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outlet Status $PDU",
   "type": "table",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "max by (alias,rPDUOutletStatusIndex) (rPDUOutletStatusOutletPhase{alias='$PDU'})  *on (alias, rPDUOutletStatusIndex) group_left (rPDUOutletStatusOutletName)(rPDUOutletStatusOutletName{alias='$PDU'})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max by (alias,rPDUOutletStatusIndex, alias) (rPDUOutletStatusOutletBank{alias='$PDU'})  *on (alias, rPDUOutletStatusIndex) group_left (rPDUOutletStatusOutletName)(rPDUOutletStatusOutletName{alias='$PDU'})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max by (alias,rPDUOutletStatusIndex) (rPDUOutletStatusLoad{alias='$PDU'})  *on (alias, rPDUOutletStatusIndex) group_left (rPDUOutletStatusOutletName)(rPDUOutletStatusOutletName{alias='$PDU'})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "max by (alias,rPDUOutletStatusIndex) (rPDUOutletStatusOutletState{alias='$PDU'})  *on (alias, rPDUOutletStatusIndex) group_left (rPDUOutletStatusOutletName)(rPDUOutletStatusOutletName{alias='$PDU'})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Info $PDU",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 20 },
   "targets": [
    {
     "expr": "rPDUIdentDeviceRating{alias='$PDU'} * on (alias) group_left (rPDUIdentDateOfManufacture)(rPDUIdentDateOfManufacture{alias='$PDU'}) * on (alias) group_left (rPDUIdentModelNumber)(rPDUIdentModelNumber{alias='$PDU'})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}