{
 "title": "Hardware Status",
 "tags": [ "hardware" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node Details",
    "query": "label_values(ipmi_bmc_info, alias)"
   }
  ]
 },
 "panels": [
  { "title": "Detail $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "Node Power Usage ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts{alias=\"$node\"}",
     "legendFormat": "Watts Main"
    },
    {
     "expr": "label_replace(ipmi_current_amperes{alias=\"$node\"} * scalar(max(ipmi_voltage_volts{alias=\"$node\"})), \"name\", \"$1\", \"name\", \".*([0-9])\")",
     "legendFormat": "Watts PS {{name}}"
    }
   ]
  },
  {
   "title": "Fan RPM",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "ipmi_fan_speed_rpm{alias=\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{alias=\"$node\"}",
     "legendFormat": "{{name}} (id {{id}})"
    }
   ]
  },
  {
   "title": "Dell HW Status",
   "type": "table",
   "description": "Dell hardware status from dellhw_exporter",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "dell_hw_chassis_status{alias=\"$node\"}",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Dell HW Components",
   "type": "table",
   "description": "Dell hardware status from dellhw_exporter",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 11 },
   "targets": [
    {
     "expr": "dell_hw_chassis_memory_status{alias=\"$node\"}",
     "legendFormat": "DIMM {{memory}}"
    },
    {
     "expr": "dell_hw_chassis_fan_status{alias=\"$node\"}",
     "legendFormat": "{{fan}}"
    },
    {
     "expr": "dell_hw_nic_status{instance=~\"$dell_hw_nic_changed\", alias=\"$node\"}",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "dell_hw_ps_status{alias=\"$node\"}",
     "legendFormat": "PS {{id}}"
    },
    {
     "expr": "dell_hw_cmos_batteries_status{alias=\"$node\"}",
     "legendFormat": "CMOS Battery {{id}}"
    },
    {
     "expr": "dell_hw_chassis_processor_status{alias=\"$node\"}",
     "legendFormat": " {{processor}}"
    },
    {
     "expr": "dell_hw_storage_battery_status{alias=\"$node\"}",
     "legendFormat": "Controller {{controller}} Batt"
    },
    {
     "expr": "dell_hw_storage_controller_status{alias=\"$node\"}",
     "legendFormat": "Controller {{id}}"
    },
    {
     "expr": "dell_hw_storage_enclosure_status{alias=\"$node\"}",
     "legendFormat": "Enclosure {{enclosure}}"
    },
    {
     "expr": "dell_hw_storage_pdisk_status{alias=\"$node\"}",
     "legendFormat": "Disk {{disk}}"
    }
   ]
  },
  {
   "title": "Dell HW Problems (timeline)",
   "type": "graph",
   "description": "Dell hardware status from dellhw_exporter",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(dell_hw_chassis_status{alias=\"$node\"} > 0) by (component)",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "IPMI Sensor States",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "ipmi_sensor_state{alias=\"$node\", type != \"Entity Presence\"} >= 0",
     "legendFormat": "{{type}} {{name}}"
    },
    {
     "expr": "ipmi_fan_speed_state{alias=\"$node\"} >= 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "IPMI Crit/Warn Sensor States (timeline)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(ipmi_sensor_state{alias=\"$node\", type != \"Entity Presence\"} > 0) by (type,name)",
     "legendFormat": "{{type}} {{name}}"
    },
    {
     "expr": "count(ipmi_fan_speed_state{alias=\"$node\"} > 0) ",
     "legendFormat": "Fans"
    }
   ]
  },
  {
   "title": "SMART Storage Devices",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "max by (alias,device)(smart_disk_status{alias=\"$node\"})  * on (alias,device) group_left (serial)(smart_disk_info)",
     "legendFormat": "{{alias}} {{device}} "
    }
   ]
  }
 ]
}