{
 "title": "Health and Alert Summary",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "temp_state_bad",
    "query": "query_result(ipmi_temperature_state > 0)"
   }
  ]
 },
 "panels": [
  { "title": "Tiles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Custer Health",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_health_status{cluster=\"production\"}"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes{cluster=\"production\"}"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes{cluster=\"production\"}"
    }
   ]
  },
  {
   "title": "OSD Down",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(ceph_osd_up == 0)" }
   ]
  },
  {
   "title": "OSD Tot",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(ceph_osd_in)" }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "description": "From IPMI sensors",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(node_uname_info)" }
   ]
  },
  {
   "title": "Total Disks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(smart_disk_info)" }
   ]
  },
  {
   "title": "Dell OM Alerts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "count(dell_hw_system_status > 0) "
    }
   ]
  },
  {
   "title": "Smart Alerts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "expr": "count(smart_disk_status > 0)" }
   ]
  },
  {
   "title": "IPMI Alerts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ipmi_sensor_state{name !~ \".*Presence.*\"} > 0)"
    }
   ]
  },
  {
   "title": "Fan Alerts",
   "type": "singlestat",
   "description": "From IPMI sensors",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ipmi_fan_speed_state > 0) "
    }
   ]
  },
  {
   "title": "Alert Rules",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "count(ALERTS{alertstate='firing'})"
    }
   ]
  },
  {
   "title": "Temp Alerts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ipmi_temperature_state > 0)"
    }
   ]
  },
  {
   "title": "Enclosure Alerts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(enclosure_status > 0)" }
   ]
  },
  { "title": "Warnings and Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Prometheus Alert Rules",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by (alertname, alias, desc) (ALERTS{alertstate='firing'})",
     "legendFormat": "{{alertname}} {{alias}} {{module}}"
    }
   ]
  },
  {
   "title": "Down OSD's",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "ceph_osd_up *on (ceph_daemon) group_left(hostname)(ceph_osd_metadata) == 0"
    }
   ]
  },
  {
   "title": "Dell HW Alerts",
   "type": "table",
   "description": "Dell hardware status from dellhw_exporter",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "max by (alias, component) (dell_hw_chassis_status) > 0",
     "legendFormat": "{{alias}} {{component}}"
    }
   ]
  },
  {
   "title": "IPMI Crit/Warn Sensor States",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 13 },
   "targets": [
    {
     "expr": "ipmi_sensor_state{name !~ \".*Presence.*\"} > 0",
     "legendFormat": "{{alias}}"
    },
    { "expr": "ipmi_fan_speed_state > 0", "legendFormat": "{{alias}}" },
    { "expr": "ipmi_temperature_state > 0", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "SMART Alerts",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "max(smart_disk_status) by (alias) > 0",
     "legendFormat": "{{alias}} {{device}} "
    }
   ]
  },
  {
   "title": "Enclosure Alerts",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "max(enclosure_status) by (alias, wwn, serial) > 0",
     "legendFormat": "{{alias}} {{device}} "
    }
   ]
  },
  {
   "title": "Switch Hardware Alerts",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "dellNetFanTrayOperStatus > 1",
     "legendFormat": "{{__name__}} Chassis {{dellNetFanDeviceIndex}} Index {{dellNetFanTrayIndex}}"
    },
    {
     "expr": "dellNetPowerSupplyOperStatus > 1",
     "legendFormat": "{{__name__}} Chassis {{dellNetPowerDeviceIndex}} Index {{dellNetPowerSupplyIndex}}"
    }
   ]
  },
  {
   "title": "Flapping Sensors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "State Changes" }
   ],
   "targets": [
    {
     "expr": "changes(ipmi_sensor_state[5m]) > 5",
     "legendFormat": "{{alias}} {{type}} {{name}}"
    },
    {
     "expr": "changes(ipmi_fan_speed_state[5m]) > 5",
     "legendFormat": "{{alias}} {{type}} {{name}}"
    },
    {
     "expr": "changes(ipmi_current_state[5m]) > 5",
     "legendFormat": "{{alias}} {{type}} {{name}}"
    },
    {
     "expr": "changes(ipmi_power_state[5m]) > 5",
     "legendFormat": "{{alias}} {{type}} {{name}}"
    },
    {
     "expr": "changes(ipmi_temperature_state[5m]) > 5",
     "legendFormat": "{{alias}} {{type}} {{name}}"
    },
    {
     "expr": "changes(dell_hw_chassis_status[5m]) > 5",
     "legendFormat": "Dell OM {{alias}} {{component}} "
    }
   ]
  },
  { "title": "Plots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "High IO",
   "type": "graph",
   "description": "These are instant rates, or a point in time figure for pending ops.  Greater than 10 ops or 1s weighted io time will show up on this plot.  Spikes are not necessarily a concern but may be useful to be aware of.  ",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_disk_io_now * on (instance,device) group_left(devname)(node_disk_info)  >= 10",
     "legendFormat": "pending {{alias}} {{devname}}"
    },
    {
     "expr": "irate(node_disk_io_time_weighted_seconds_total[5m]) * on (instance,device) group_left(devname)(node_disk_info) > 1",
     "legendFormat": "time {{alias}} {{devname}}"
    }
   ]
  },
  {
   "title": "High CPU",
   "type": "graph",
   "description": "Plotted with irate.  Will capture instantaneous spikes of CPU usage exceeding 50%.   These are not necessarily alarming if not constant but can be useful to be aware of.  \n",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) without (cpu)) / count(node_cpu_seconds_total) without (cpu) *100  > 50",
     "legendFormat": "{{mode}} {{alias}}"
    }
   ]
  },
  {
   "title": "Temperature Warn/Crit Value Plots ",
   "type": "graph",
   "description": "Plots for IPMI temp sensors in warn or critical states.  This panel will be empty if there are no sensors in warn or crit state.  ",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{instance=\"$temp_state_bad\"}",
     "legendFormat": "{{alias}} {{name}} (id {{id}})"
    }
   ]
  },
  {
   "title": "Chassis Temp Avg (inlet)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 36 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg (ipmi_temperature_celsius{name=\"Inlet Temp\"}) by (site)",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Total Power Usage (not incl storage encl)",
   "type": "graph",
   "description": "Sum of power usage reported by IPMI sensors",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "sum (ipmi_dcmi_power_consumption_watts) by (site)",
     "legendFormat": "{{site}}"
    }
   ]
  }
 ]
}