{
 "title": "Multi-Node Disk Device Stats",
 "description": "Disk IO stats with selectable nodes/devices in single plots",
 "tags": [
  "disk",
  "combined"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_boot_time_seconds, alias)"
   },
   {
    "name": "deviceFilter",
    "query": "sd,vd,rbd,nvme,mpath,vg,vgdb,vgdata"
   },
   {
    "name": "device",
    "query": "label_values(node_disk_info{devname=~\"$deviceFilter.*\"},devname)"
   },
   {
    "name": "interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Bytes / Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{alias=~\"$node\"}[5m]) * on (instance,device) group_left(devname)(node_disk_info{devname=~\"$device\"})",
     "legendFormat": "{{alias}} {{devname}} - read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{alias=~\"$node\"}[5m]) * on (instance,device) group_left(devname)(node_disk_info{devname=~\"$device\"})",
     "legendFormat": "{{alias}} {{devname}} - write"
    }
   ]
  },
  {
   "title": "Ops / sec (read inverted)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{alias=~\"$node\"}[5m]) * on (instance,device) group_left(devname)(node_disk_info{devname=~\"$device\"})",
     "legendFormat": "{{alias}} {{devname}} - reads"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{alias=~\"$node\"}[5m]) * on (instance,device) group_left(devname)(node_disk_info{devname=~\"$device\"})\n",
     "legendFormat": "{{alias}} {{devname}} - writes"
    }
   ]
  },
  {
   "title": "Time (weighted time  inverted)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{alias=~\"$node\"}[5m]) * on (instance,device) group_left(devname)(node_disk_info{devname=~\"$device\"})",
     "legendFormat": "{{alias}} {{devname}} - time"
    },
    {
     "expr": "irate(node_disk_io_time_weighted_seconds_total{alias=~\"$node\"}[5m]) * on (instance,device) group_left(devname)(node_disk_info{devname=~\"$device\"})\n",
     "legendFormat": "{{alias}} {{devname}} - weighted time"
    }
   ]
  },
  {
   "title": "Ops In Progress (pending ops)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_disk_io_now{alias=~\"$node\"} * on (instance,device) group_left(devname)(node_disk_info{devname=~\"$device\"})",
     "legendFormat": "{{alias}} {{devname}} - in progress"
    }
   ]
  },
  {
   "title": "Merged (read inverted)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_merged_total{alias=~\"$node\"}[5m]) * on (instance,device) group_left(devname)(node_disk_info{devname=~\"$device\"})\n",
     "legendFormat": "{{alias}} {{devname}} - reads"
    },
    {
     "expr": "irate(node_disk_writes_merged_total{alias=~\"$node\"}[5m]) * on (instance,device) group_left(devname)(node_disk_info{devname=~\"$device\"})\n",
     "legendFormat": "{{alias}} {{devname}} - writes"
    }
   ]
  }
 ]
}