{
 "title": "Node Performance",
 "tags": [
  "disk",
  "cpu",
  "network"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(node_uname_info, alias)"
   },
   {
    "name": "interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "deviceFilter",
    "label": "Disk Filter",
    "query": "sd,vd,rbd,nvme,mpath,vg,vgdb,vgdata"
   },
   {
    "name": "device",
    "label": "Disk Devices",
    "query": "label_values(node_disk_info{devname=~\"$deviceFilter.*\"},devname)"
   },
   {
    "name": "ndevice",
    "label": "Network Devices",
    "query": "label_values(node_network_info{alias=~\"$host\"},device)"
   }
  ]
 },
 "panels": [
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  {
   "title": "$host Overall Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{alias=\"$host\"}",
     "legendFormat": "1 minute avg"
    },
    {
     "expr": "node_load5{alias=\"$host\"}",
     "legendFormat": "5 minute avg"
    },
    {
     "expr": "node_load15{alias=\"$host\"}",
     "legendFormat": "15 minute avg"
    }
   ]
  },
  {
   "title": "$host CPU Time ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(node_cpu_seconds_total {mode!=\"idle\", alias=\"$host\"} [5m])) without (cpu)) / count(node_cpu_seconds_total{alias=\"$host\"}) without (cpu) *100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "$host memory",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{alias=\"$host\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{alias=\"$host\"} - node_memory_MemFree_bytes{alias=\"$host\"} - (node_memory_Cached_bytes{alias=\"$host\"} + node_memory_Buffers_bytes{alias=\"$host\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{alias=\"$host\"} + node_memory_Buffers_bytes{alias=\"$host\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{alias=\"$host\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{alias=\"$host\"} - node_memory_SwapFree_bytes{alias=\"$host\"})",
     "legendFormat": "SWAP Used"
    },
    {
     "expr": "node_memory_SwapFree_bytes{alias=\"$host\"}",
     "legendFormat": "SWAP Free"
    }
   ]
  },
  {
   "title": "Network $host: Bytes/s (RX inverted)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{alias=\"$host\", device=~\"$ndevice\"}[5m])",
     "legendFormat": "RX {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"$host\", device=~\"$ndevice\"}[5m])",
     "legendFormat": "TX {{device}}"
    }
   ]
  },
  {
   "title": "Interface Errors",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_errs_total{alias=~\"$node\"}[5m])",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{alias=~\"$node\"}[5m])",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "$host: Disk I/O time (un-weighted inverted)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_weighted_seconds_total{alias=~\"$host\"}[5m]) * on (instance,device) group_left(devname)(node_disk_info{devname=~\"$device\"})\n",
     "legendFormat": "weighted {{devname}}"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{alias=~\"$host\"}[5m]) * on (instance,device) group_left(devname)(node_disk_info{devname=~\"$device\"})",
     "legendFormat": "unweighted {{devname}}"
    }
   ]
  },
  {
   "title": "$host: Disk Pending Ops",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_disk_io_now{alias=~\"$host\"} * on (instance,device) group_left(devname)(node_disk_info{devname=~\"$device\"})",
     "legendFormat": "Pending ops {{devname}}"
    }
   ]
  },
  {
   "title": "$host: Disk Bytes (Read inverted)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{alias=~\"$host\"}[5m]) * on (instance,device) group_left(devname)(node_disk_info{devname=~\"$device\"})",
     "legendFormat": "read {{devname}}"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{alias=~\"$host\"}[5m]) * on (instance,device) group_left(devname)(node_disk_info{devname=~\"$device\"})",
     "legendFormat": "write {{devname}}"
    }
   ]
  },
  {
   "title": "$host: Disk IOPS (Read inverted)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{alias=~\"$host\"}[5m]) * on (instance,device) group_left(devname)(node_disk_info{devname=~\"$device\"})",
     "legendFormat": "read {{devname}}"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{alias=~\"$host\"}[5m]) * on (instance,device) group_left(devname)(node_disk_info{devname=~\"$device\"})\n",
     "legendFormat": "write {{devname}}"
    }
   ]
  }
 ]
}