{
 "title": "SC19 Multi-node Network Interface Stats",
 "description": "IO and error stats for selectable set of nodes.  Per-node and combined plots.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_network_info, alias)"
   },
   {
    "name": "device",
    "query": "label_values(node_network_info{alias=~\"$node\"},device)"
   },
   {
    "name": "interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Summaries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Combined Network Traffic Bytes (recv inverted)",
   "type": "graph",
   "description": "Basic network info per interface for all selected nodes",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{alias=~\"$node\",device=~\"$device\"}[5m])",
     "legendFormat": "recv {{alias}} {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=~\"$node\",device=~\"$device\"}[5m])",
     "legendFormat": "trans {{alias}} {{device}}"
    }
   ]
  },
  {
   "title": "Combined Network Traffic Packets",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{alias=~\"$node\",device=~\"$device\"}[5m])",
     "legendFormat": "recv {{alias}} {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{alias=~\"$node\",device=~\"$device\"}[5m])",
     "legendFormat": "trans {{alias}} {{device}}"
    }
   ]
  },
  {
   "title": "Interface Errors (Selected interfaces)",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_errs_total{alias=~\"$node\",device=~\"$device\"}[5m])",
     "legendFormat": "recv {{alias}} {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{alias=~\"$node\",device=~\"$device\"}[5m])",
     "legendFormat": "trans {{alias}} {{device}} "
    }
   ]
  },
  {
   "title": "Nodes with non-zero interface errors",
   "type": "graph",
   "description": "All nodes with non-zero error counters.  Not effected by the node/device selector.  ",
   "gridPos": { "h": 6, "w": 10, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_errs_total[5m]) > 0",
     "legendFormat": "recv {{device}} {{alias}}"
    },
    {
     "expr": "irate(node_network_transmit_errs_total[5m]) > 0",
     "legendFormat": "trans {{device}} {{alias}}"
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "node" },
  {
   "title": "Network Traffic Bytes (recv inverted)",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{alias=\"$node\",device=~\"$device\"}[5m])",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"$node\",device=~\"$device\"}[5m])",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic Packets",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{alias=~\"$node\",device=~\"$device\"}[5m])",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{alias=~\"$node\",device=~\"$device\"}[5m])",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  {
   "title": "Interface Errors (Selected interfaces)",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_errs_total{alias=~\"$node\",device=~\"$device\"}[5m])",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{alias=~\"$node\",device=~\"$device\"}[5m])",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Network Traffic Bytes (recv inverted)",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{alias=\"$node\",device=~\"$device\"}[5m])",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"$node\",device=~\"$device\"}[5m])",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic Packets",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{alias=~\"$node\",device=~\"$device\"}[5m])",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{alias=~\"$node\",device=~\"$device\"}[5m])",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  {
   "title": "Interface Errors (Selected interfaces)",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_errs_total{alias=~\"$node\",device=~\"$device\"}[5m])",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{alias=~\"$node\",device=~\"$device\"}[5m])",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Network Traffic Bytes (recv inverted)",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{alias=\"$node\",device=~\"$device\"}[5m])",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{alias=\"$node\",device=~\"$device\"}[5m])",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic Packets",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{alias=~\"$node\",device=~\"$device\"}[5m])",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_packets_total{alias=~\"$node\",device=~\"$device\"}[5m])",
     "legendFormat": "trans {{device}}"
    }
   ]
  },
  {
   "title": "Interface Errors (Selected interfaces)",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_errs_total{alias=~\"$node\",device=~\"$device\"}[5m])",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{alias=~\"$node\",device=~\"$device\"}[5m])",
     "legendFormat": "trans {{device}} "
    }
   ]
  }
 ]
}