{
 "title": "Storage Enclosure Details",
 "tags": [
  "disk",
  "enclosure"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(enclosure_status, alias)"
   },
   {
    "name": "serial",
    "query": "label_values(enclosure_status{alias=\"$host\"}, enclosure_serial)"
   }
  ]
 },
 "panels": [
  { "title": "Status $serial", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "serial" },
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by (alias,enclosure_name, enclosure_serial, enclosure_wwn) (enclosure_status{alias=\"$host\"})",
     "legendFormat": "{{alias}} {{device}} "
    }
   ]
  },
  {
   "title": "Enclosure Slots",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "max by (enclosure_slot, drawer_slot, drawer) (enclosure_slot_status{alias=\"$host\"})",
     "legendFormat": "{{alias}} {{device}} "
    }
   ]
  },
  {
   "title": "Enclosure Fans",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 4 },
   "targets": [
    {
     "expr": "max by (name) (enclosure_fan_status{alias=\"$host\"})",
     "legendFormat": "{{alias}} {{device}} "
    }
   ]
  },
  {
   "title": "Enclosure Power ",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "max by (name) (enclosure_power_status{alias=\"$host\"})",
     "legendFormat": "{{alias}} {{device}} "
    },
    {
     "expr": "max by (name) (enclosure_power_ac_status{alias=\"$host\"})",
     "legendFormat": "{{alias}} {{device}} "
    },
    {
     "expr": "max by (name) (enclosure_power_dc_status{alias=\"$host\"})",
     "legendFormat": "{{alias}} {{device}} "
    }
   ]
  },
  {
   "title": "Enclosure Temp Sensors",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "max by (name) (enclosure_temp_status{alias=\"$host\"})",
     "legendFormat": "{{alias}} {{device}} "
    }
   ]
  },
  {
   "title": "Enclosure Voltage",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "max by (name) (enclosure_voltage_status{alias=\"$host\"})",
     "legendFormat": "{{alias}} {{device}} "
    },
    {
     "expr": "max by (name) (enclosure_voltage_under_status{alias=\"$host\"})",
     "legendFormat": "{{alias}} {{device}} "
    },
    {
     "expr": "max by (name) (enclosure_voltage_over_status{alias=\"$host\"})",
     "legendFormat": "{{alias}} {{device}} "
    }
   ]
  },
  {
   "title": "Fan Speeds (RPM)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "enclosure_fan_speed_rpm{alias=\"$host\"}",
     "legendFormat": "{{name}} "
    }
   ]
  },
  {
   "title": "Enclosure Temps (C)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "enclosure_temp_celsius{alias=\"$host\"}",
     "legendFormat": "{{name}} "
    }
   ]
  }
 ]
}