{
 "title": "Storage Information",
 "tags": [
  "hardware",
  "disk"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "allhosts",
    "query": "label_values(smart_disk_status, alias)"
   },
   {
    "name": "host",
    "label": "Detail Hosts",
    "query": "label_values(smart_disk_status, alias)"
   },
   {
    "name": "attributes",
    "query": "label_values(smart_disk_attr_total, name)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Status Roundup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Failed Devices",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(smart_disk_status) by (alias, device) * on (alias, device) group_left (serial)(smart_disk_info)> 0",
     "legendFormat": "{{alias}} - {{device}} - {{serial}}"
    },
    {
     "expr": "(dell_hw_storage_pdisk_status > 0) + 1",
     "legendFormat": "{{alias}} - Dell cntrl{{controller}} disk {{disk}}"
    },
    {
     "expr": "(dell_hw_storage_vdisk_status > 0) + 1",
     "legendFormat": "{{alias}} - Dell vdisk {{vdisk}}"
    }
   ]
  },
  {
   "title": "Failed Devices by OSD",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "max without (job, site,cluster)(ceph_osd_device_info) * on (instance,device) group_left  (Value)(smart_disk_status) > 0",
     "legendFormat": "{{alias}} {{device}} "
    }
   ]
  },
  {
   "title": "Failed Devices by Enclosure",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "max(smart_disk_status) by (alias, device) * on (alias, device) group_left (serial)(smart_disk_info) * on (alias,serial) group_left ( enclosure_slot, enclosure_serial,drawer, drawer_slot)(enclosure_drive_info) >0",
     "legendFormat": "{{alias}} {{device}} "
    }
   ]
  },
  {
   "title": "Enclosure Hardware",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "max(enclosure_slot_status) by (alias, enclosure_wwn, enclosure_serial)",
     "legendFormat": "{{alias}} {{device}} "
    },
    {
     "expr": "max(enclosure_temp_status) by (alias, enclosure_wwn, enclosure_serial)",
     "legendFormat": "{{alias}} {{device}} "
    },
    {
     "expr": "max(enclosure_fan_status) by (alias, enclosure_wwn, enclosure_serial)",
     "legendFormat": "{{alias}} {{device}} "
    },
    {
     "expr": "max(enclosure_voltage_status) by (alias, enclosure_wwn, enclosure_serial)",
     "legendFormat": "{{alias}} {{device}} "
    },
    {
     "expr": "max(enclosure_power_status) by (alias, enclosure_wwn, enclosure_serial)",
     "legendFormat": "{{alias}} {{device}} "
    },
    {
     "expr": "max(enclosure_status) by (alias, enclosure_wwn, enclosure_serial)",
     "legendFormat": "{{alias}} {{device}} "
    }
   ]
  },
  {
   "title": "Down OSD device list ",
   "type": "table",
   "description": "OSD marked down along with all known devices from LVM metadata.  If an OSD is here but has no devices with problems it is either down for other reasons (marked down, network, etc) or one of the devices has gone missing.  ",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "max without (job, site,cluster)(ceph_osd_device_info) * on (ceph_daemon) group_left ()(ceph_osd_up) ==0",
     "legendFormat": "{{alias}} {{}} "
    }
   ]
  },
  { "title": "Warning Attributes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "SSD/NVMe Near EOL (20%)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "smart_disk_lifetime_percent * on (instance,device) group_left(model,serial)(smart_disk_info) <= 20",
     "legendFormat": "{{alias}} {{device}} {{model}} {{serial}}"
    }
   ]
  },
  {
   "title": "Non-Zero Failure Attributes (rate is inverted)",
   "type": "graph",
   "description": "SMART attributes which may indicate failure if non-zero.  Some, such as reallocated sectors, may not be an issue if they are not increasing rapidly.  Some of these attributes may additionally trip SMART to indicate failure status when they cross certain thresholds.  ",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "smart_disk_attr_total * on (instance,device) group_left(model,serial)(smart_disk_info) > 0",
     "legendFormat": "{{name}} -- {{alias}} {{device}} {{model}} {{serial}}"
    },
    {
     "expr": "rate(smart_disk_attr_total[5m]) * on (instance,device) group_left(model,serial)(smart_disk_info) > 0",
     "legendFormat": "rate {{name}} -- {{alias}} {{device}} {{model}} {{serial}}"
    }
   ]
  },
  { "title": "Host Details $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }, "repeat": "host" },
  {
   "title": "Disk Temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "smart_disk_temperature_celsius{alias=\"$host\"} * on (instance,device) group_left(model,serial)(smart_disk_info) ",
     "legendFormat": "{{device}} {{model}} {{serial}}"
    }
   ]
  },
  {
   "title": "LIfetime Remaining",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "smart_disk_lifetime_percent{alias=\"$host\"} * on (instance,device) group_left(model,serial)(smart_disk_info) ",
     "legendFormat": "{{device}} {{model}} {{serial}}"
    }
   ]
  },
  {
   "title": "Attribute $attributes (non-zero only)",
   "type": "graph",
   "description": "Rate of change is inverted ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "repeat": "attributes",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "smart_disk_attr_total{alias=\"$host\", name=\"$attributes\"} * on (instance,device) group_left(model,serial)(smart_disk_info) > 0",
     "legendFormat": "{{device}} {{model}} {{serial}}"
    },
    {
     "expr": "rate(smart_disk_attr_total{alias=\"$host\", name=\"$attributes\"}[5m]) * on (instance,device) group_left(model,serial)(smart_disk_info) > 0",
     "legendFormat": "rate {{device}}  {{model}} {{serial}}"
    }
   ]
  },
  {
   "title": "Attribute $attributes (non-zero only)",
   "type": "graph",
   "description": "Rate of change is inverted ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "smart_disk_attr_total{alias=\"$host\", name=\"$attributes\"} * on (instance,device) group_left(model,serial)(smart_disk_info) > 0",
     "legendFormat": "{{device}} {{model}} {{serial}}"
    },
    {
     "expr": "rate(smart_disk_attr_total{alias=\"$host\", name=\"$attributes\"}[5m]) * on (instance,device) group_left(model,serial)(smart_disk_info) > 0",
     "legendFormat": "rate {{device}}  {{model}} {{serial}}"
    }
   ]
  },
  {
   "title": "Attribute $attributes (non-zero only)",
   "type": "graph",
   "description": "Rate of change is inverted ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "smart_disk_attr_total{alias=\"$host\", name=\"$attributes\"} * on (instance,device) group_left(model,serial)(smart_disk_info) > 0",
     "legendFormat": "{{device}} {{model}} {{serial}}"
    },
    {
     "expr": "rate(smart_disk_attr_total{alias=\"$host\", name=\"$attributes\"}[5m]) * on (instance,device) group_left(model,serial)(smart_disk_info) > 0",
     "legendFormat": "rate {{device}}  {{model}} {{serial}}"
    }
   ]
  },
  {
   "title": "Attribute $attributes (non-zero only)",
   "type": "graph",
   "description": "Rate of change is inverted ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "smart_disk_attr_total{alias=\"$host\", name=\"$attributes\"} * on (instance,device) group_left(model,serial)(smart_disk_info) > 0",
     "legendFormat": "{{device}} {{model}} {{serial}}"
    },
    {
     "expr": "rate(smart_disk_attr_total{alias=\"$host\", name=\"$attributes\"}[5m]) * on (instance,device) group_left(model,serial)(smart_disk_info) > 0",
     "legendFormat": "rate {{device}}  {{model}} {{serial}}"
    }
   ]
  }
 ]
}