{
 "title": "Switch Interfaces Stacked",
 "tags": [ "network" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "query": "label_values(ifInOctets, instance)"
   },
   {
    "name": "interfaces",
    "query": "label_values(ifInOctets{instance=~\"$device\"}, ifAlias)"
   },
   {
    "name": "interval",
    "query": "10s,30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Stacked", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Stacked Interface Throughput",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifAlias=~\"$interfaces\"}[5m]) * 8",
     "legendFormat": "RX {{alias}} - {{ifAlias}} ({{ifDescr}})"
    },
    {
     "expr": "irate(ifHCOutOctets{ifAlias=~\"$interfaces\"}[5m]) * 8",
     "legendFormat": "TX {{alias}} - {{ifAlias}} ({{ifDescr}})"
    }
   ]
  },
  { "title": "Unstacked", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Interface Throughput",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifAlias=~\"$interfaces\"}[5m]) * 8",
     "legendFormat": "RX {{alias}} - {{ifAlias}} ({{ifDescr}})"
    },
    {
     "expr": "irate(ifHCOutOctets{ifAlias=~\"$interfaces\"}[5m]) * 8",
     "legendFormat": "TX {{alias}} - {{ifAlias}} ({{ifDescr}})"
    }
   ]
  },
  { "title": "Errors and Discards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none", "label": "errors" }
   ],
   "targets": [
    {
     "expr": "irate(ifOutErrors{ifAlias=~\"$interfaces\"}[1m])",
     "legendFormat": "{{alias}} - {{ifAlias}} ({{ifDescr}}) Out Errors"
    },
    {
     "expr": "irate(ifInErrors{ifAlias=~\"$interfaces\"}[1m])",
     "legendFormat": "{{alias}} - {{ifAlias}} ({{ifDescr}}) In Errors"
    }
   ]
  },
  {
   "title": "Discards",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none", "label": "discards" }
   ],
   "targets": [
    {
     "expr": "irate(ifOutDiscards{ifAlias=~\"$interfaces\"}[1m]) ",
     "legendFormat": "{{alias}} - {{ifAlias}} ({{ifDescr}}) Out Discards"
    },
    {
     "expr": "irate(ifInDiscards{ifAlias=~\"$interfaces\"}[1m])",
     "legendFormat": "{{alias}} - {{ifAlias}} ({{ifDescr}}) In Discards"
    }
   ]
  }
 ]
}