{
 "title": "Switch Summary",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "toprate",
    "query": "query_result(topk(3,irate(ifHCInOctets[${__range_s}s])))"
   },
   {
    "name": "device",
    "query": "label_values(ifInOctets, instance)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Summaries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Errors Detected",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "errors" }
   ],
   "targets": [
    {
     "expr": "irate(ifOutErrors[5m])",
     "legendFormat": "{{alias}} {{ifAlias}} ({{ifDescr}}) Out Errors"
    },
    {
     "expr": "irate(ifInErrors[5m])",
     "legendFormat": "{{alias}} {{ifAlias}} ({{ifDescr}}) In Errors"
    }
   ]
  },
  {
   "title": "Inter-Site Traffic UMich (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{alias=\"um-sw01\", ifDescr=\"hundredGigE 1/29\"}[5m])",
     "legendFormat": "100G MiLR TX to WSU"
    },
    {
     "expr": "irate(ifHCInOctets{alias=\"um-sw01\", ifDescr=\"hundredGigE 1/29\"}[5m])",
     "legendFormat": "100G MiLR RX from WSU"
    },
    {
     "expr": "irate(ifHCOutOctets{alias=\"um-sw01\", ifDescr=\"hundredGigE 1/30\"}[5m])",
     "legendFormat": "100G MiLR TX to MSU"
    },
    {
     "expr": "irate(ifHCInOctets{alias=\"um-sw01\", ifDescr=\"hundredGigE 1/30\"}[5m])",
     "legendFormat": "100G MiLR RX from MSU"
    },
    {
     "expr": "irate(ifHCInOctets{alias=\"um-sw01\", ifDescr=\"fortyGigE 1/27/1\"}[5m])",
     "legendFormat": "40G Datacenter RX (all sites)"
    },
    {
     "expr": "irate(ifHCOutOctets{alias=\"um-sw01\", ifDescr=\"fortyGigE 1/27/1\"}[5m])",
     "legendFormat": "40G Datacenter TX (all sites)"
    }
   ]
  },
  {
   "title": "Ports Up",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(ifAdminStatus == 1)", "legendFormat": "Admin Up" },
    { "expr": "count(ifOperStatus ==1) ", "legendFormat": "Status Up" },
    { "expr": "count(ifConnectorPresent == 1)", "legendFormat": "Link Phys" }
   ]
  },
  {
   "title": "Inter-Site Traffic Wayne (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{alias=\"wsu-sw01\", ifDescr=\"hundredGigE 1/29\"}[5m])",
     "legendFormat": "100G MiLR RX from UM"
    },
    {
     "expr": "irate(ifHCOutOctets{alias=\"wsu-sw01\", ifDescr=\"hundredGigE 1/29\"}[5m])",
     "legendFormat": "100G MiLR TX to UM"
    },
    {
     "expr": "irate(ifHCInOctets{alias=\"wsu-sw01\", ifDescr=\"hundredGigE 1/30\"}[5m])",
     "legendFormat": "100G MiLR RX from MSU"
    },
    {
     "expr": "irate(ifHCInOctets{alias=\"wsu-sw01\", ifDescr=\"hundredGigE 1/30\"}[5m])",
     "legendFormat": "100G MiLR TX to MSU"
    },
    {
     "expr": "irate(ifHCOutOctets{alias=\"wsu-sw01\", ifDescr=\"TenGigabitEthernet 1/34\"}[5m])",
     "legendFormat": "10G TX Datacenter (all sites)"
    },
    {
     "expr": "irate(ifHCInOctets{alias=\"wsu-sw01\", ifDescr=\"TenGigabitEthernet 1/34\"}[5m])",
     "legendFormat": "10G RX Datacenter (all sites)"
    }
   ]
  },
  {
   "title": "Recent State Changes",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "bottomk(10,sort_desc(sysUpTime/100 - on (instance) group_right ifLastChange/100))"
    }
   ]
  },
  {
   "title": "Inter-Site Traffic MichState (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{alias=\"msu-sw02\", ifDescr=\"hundredGigE 1/29\"}[5m])",
     "legendFormat": "100G MiLR RX from WSU"
    },
    {
     "expr": "irate(ifHCOutOctets{alias=\"msu-sw02\", ifDescr=\"hundredGigE 1/29\"}[5m])",
     "legendFormat": "100G MiLR TX to WSU"
    },
    {
     "expr": "irate(ifHCInOctets{alias=\"msu-sw02\", ifDescr=\"hundredGigE 1/30\"}[5m])",
     "legendFormat": "100G MiLR RX from UM"
    },
    {
     "expr": "irate(ifInOctets{alias=\"msu-sw02\", ifDescr=\"hundredGigE 1/30\"}[5m])",
     "legendFormat": "100G MiLR TX to UM"
    },
    {
     "expr": "irate(ifHCOutOctets{alias=\"msu-sw02\", ifDescr=\"Port-channel 12\"}[5m])",
     "legendFormat": "80G AGLT2 TX to UM"
    },
    {
     "expr": "irate(ifHCInOctets{alias=\"msu-sw02\", ifDescr=\"Port-channel 12\"}[5m])",
     "legendFormat": "80G AGLT2 RX from UM"
    },
    {
     "expr": "irate(ifHCOutOctets{alias=\"msu-sw02\", ifDescr=\"fortyGigE 1/2/1\"}[5m])",
     "legendFormat": "40G Datacenter TX (all sites)"
    },
    {
     "expr": "irate(ifHCInOctets{alias=\"msu-sw02\", ifDescr=\"fortyGigE 1/2/1\"}[5m])",
     "legendFormat": "40G Datacenter RX (all sites)"
    }
   ]
  },
  {
   "title": "Hardware Alerts",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "dellNetFanTrayOperStatus{alias=\"$device\"} > 1",
     "legendFormat": "{{__name__}} Chassis {{dellNetFanDeviceIndex}} Index {{dellNetFanTrayIndex}}"
    },
    {
     "expr": "dellNetPowerSupplyOperStatus{alias=\"$device\"} > 1",
     "legendFormat": "{{__name__}} Chassis {{dellNetPowerDeviceIndex}} Index {{dellNetPowerSupplyIndex}}"
    }
   ]
  },
  {
   "title": "Top 3 Throughput (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 22 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifAlias=~\"$toprate\"}[5m])",
     "legendFormat": "RX {{alias}} - {{ifAlias}}"
    },
    {
     "expr": "irate(ifHCOutOctets{ifAlias=~\"$toprate\"}[5m])",
     "legendFormat": "TX {{alias}} -  {{ifAlias}}"
    }
   ]
  },
  { "title": "$device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }, "repeat": "device" },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "Switch management uptime",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 30 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sysUpTime{alias=\"$device\"} /100"
    }
   ]
  },
  {
   "title": "Total Throughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 3, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ifOutOctets{alias=\"$device\"}[1m]))",
     "legendFormat": "Outbound"
    },
    {
     "expr": "sum(irate(ifInOctets{alias=\"$device\"}[1m]))",
     "legendFormat": "Inbound"
    }
   ]
  },
  {
   "title": "Ports Up",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(ifAdminStatus{alias=\"$device\"} == 1)",
     "legendFormat": "Admin Up"
    },
    {
     "expr": "count(ifOperStatus{alias=\"$device\"} == 1)",
     "legendFormat": "Status Up"
    },
    {
     "expr": "count(ifConnectorPresent{alias=\"$device\"} == 1)",
     "legendFormat": "Link Phys"
    }
   ]
  },
  {
   "title": "Errors Detected",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "none", "label": "errors" }
   ],
   "targets": [
    {
     "expr": "irate(ifOutErrors{alias=\"$device\"}[5m])",
     "legendFormat": "{{ifAlias}} ({{ifDescr}}) Out Errors"
    },
    {
     "expr": "irate(ifInErrors{alias=\"$device\"}[5m])",
     "legendFormat": "{{ifAlias}} ({{ifDescr}}) In Errors"
    }
   ]
  },
  {
   "title": "Hardware Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "dellNetFanTrayOperStatus{alias=\"$device\"}",
     "legendFormat": "{{__name__}} Chassis {{dellNetFanDeviceIndex}} Index {{dellNetFanTrayIndex}}"
    },
    {
     "expr": "dellNetPowerSupplyOperStatus{alias=\"$device\"}",
     "legendFormat": "{{__name__}} Chassis {{dellNetPowerDeviceIndex}} Index {{dellNetPowerSupplyIndex}}"
    }
   ]
  },
  {
   "title": "Resource Utilization %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(dellNetCpuUtil5Sec{alias=\"$device\"})",
     "legendFormat": "CPU "
    },
    {
     "expr": "dellNetCpuUtilMemUsage{alias=\"$device\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "dellNetCpuFlashUsage{alias=\"$device\"}",
     "legendFormat": "Flash"
    }
   ]
  },
  { "title": "$device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "Switch management uptime",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 41 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sysUpTime{alias=\"$device\"} /100"
    }
   ]
  },
  {
   "title": "Total Throughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 3, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ifOutOctets{alias=\"$device\"}[1m]))",
     "legendFormat": "Outbound"
    },
    {
     "expr": "sum(irate(ifInOctets{alias=\"$device\"}[1m]))",
     "legendFormat": "Inbound"
    }
   ]
  },
  {
   "title": "Ports Up",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(ifAdminStatus{alias=\"$device\"} == 1)",
     "legendFormat": "Admin Up"
    },
    {
     "expr": "count(ifOperStatus{alias=\"$device\"} == 1)",
     "legendFormat": "Status Up"
    },
    {
     "expr": "count(ifConnectorPresent{alias=\"$device\"} == 1)",
     "legendFormat": "Link Phys"
    }
   ]
  },
  {
   "title": "Errors Detected",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "none", "label": "errors" }
   ],
   "targets": [
    {
     "expr": "irate(ifOutErrors{alias=\"$device\"}[5m])",
     "legendFormat": "{{ifAlias}} ({{ifDescr}}) Out Errors"
    },
    {
     "expr": "irate(ifInErrors{alias=\"$device\"}[5m])",
     "legendFormat": "{{ifAlias}} ({{ifDescr}}) In Errors"
    }
   ]
  },
  {
   "title": "Hardware Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "dellNetFanTrayOperStatus{alias=\"$device\"}",
     "legendFormat": "{{__name__}} Chassis {{dellNetFanDeviceIndex}} Index {{dellNetFanTrayIndex}}"
    },
    {
     "expr": "dellNetPowerSupplyOperStatus{alias=\"$device\"}",
     "legendFormat": "{{__name__}} Chassis {{dellNetPowerDeviceIndex}} Index {{dellNetPowerSupplyIndex}}"
    }
   ]
  },
  {
   "title": "Resource Utilization %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(dellNetCpuUtil5Sec{alias=\"$device\"})",
     "legendFormat": "CPU "
    },
    {
     "expr": "dellNetCpuUtilMemUsage{alias=\"$device\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "dellNetCpuFlashUsage{alias=\"$device\"}",
     "legendFormat": "Flash"
    }
   ]
  },
  { "title": "$device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "Switch management uptime",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 52 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sysUpTime{alias=\"$device\"} /100"
    }
   ]
  },
  {
   "title": "Total Throughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 3, "y": 52 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ifOutOctets{alias=\"$device\"}[1m]))",
     "legendFormat": "Outbound"
    },
    {
     "expr": "sum(irate(ifInOctets{alias=\"$device\"}[1m]))",
     "legendFormat": "Inbound"
    }
   ]
  },
  {
   "title": "Ports Up",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(ifAdminStatus{alias=\"$device\"} == 1)",
     "legendFormat": "Admin Up"
    },
    {
     "expr": "count(ifOperStatus{alias=\"$device\"} == 1)",
     "legendFormat": "Status Up"
    },
    {
     "expr": "count(ifConnectorPresent{alias=\"$device\"} == 1)",
     "legendFormat": "Link Phys"
    }
   ]
  },
  {
   "title": "Errors Detected",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "none", "label": "errors" }
   ],
   "targets": [
    {
     "expr": "irate(ifOutErrors{alias=\"$device\"}[5m])",
     "legendFormat": "{{ifAlias}} ({{ifDescr}}) Out Errors"
    },
    {
     "expr": "irate(ifInErrors{alias=\"$device\"}[5m])",
     "legendFormat": "{{ifAlias}} ({{ifDescr}}) In Errors"
    }
   ]
  },
  {
   "title": "Hardware Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "dellNetFanTrayOperStatus{alias=\"$device\"}",
     "legendFormat": "{{__name__}} Chassis {{dellNetFanDeviceIndex}} Index {{dellNetFanTrayIndex}}"
    },
    {
     "expr": "dellNetPowerSupplyOperStatus{alias=\"$device\"}",
     "legendFormat": "{{__name__}} Chassis {{dellNetPowerDeviceIndex}} Index {{dellNetPowerSupplyIndex}}"
    }
   ]
  },
  {
   "title": "Resource Utilization %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(dellNetCpuUtil5Sec{alias=\"$device\"})",
     "legendFormat": "CPU "
    },
    {
     "expr": "dellNetCpuUtilMemUsage{alias=\"$device\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "dellNetCpuFlashUsage{alias=\"$device\"}",
     "legendFormat": "Flash"
    }
   ]
  },
  { "title": "$device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "Switch management uptime",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 63 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sysUpTime{alias=\"$device\"} /100"
    }
   ]
  },
  {
   "title": "Total Throughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 3, "y": 63 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ifOutOctets{alias=\"$device\"}[1m]))",
     "legendFormat": "Outbound"
    },
    {
     "expr": "sum(irate(ifInOctets{alias=\"$device\"}[1m]))",
     "legendFormat": "Inbound"
    }
   ]
  },
  {
   "title": "Ports Up",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(ifAdminStatus{alias=\"$device\"} == 1)",
     "legendFormat": "Admin Up"
    },
    {
     "expr": "count(ifOperStatus{alias=\"$device\"} == 1)",
     "legendFormat": "Status Up"
    },
    {
     "expr": "count(ifConnectorPresent{alias=\"$device\"} == 1)",
     "legendFormat": "Link Phys"
    }
   ]
  },
  {
   "title": "Errors Detected",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 63 },
   "yaxes": [
    { "format": "none", "label": "errors" }
   ],
   "targets": [
    {
     "expr": "irate(ifOutErrors{alias=\"$device\"}[5m])",
     "legendFormat": "{{ifAlias}} ({{ifDescr}}) Out Errors"
    },
    {
     "expr": "irate(ifInErrors{alias=\"$device\"}[5m])",
     "legendFormat": "{{ifAlias}} ({{ifDescr}}) In Errors"
    }
   ]
  },
  {
   "title": "Hardware Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "dellNetFanTrayOperStatus{alias=\"$device\"}",
     "legendFormat": "{{__name__}} Chassis {{dellNetFanDeviceIndex}} Index {{dellNetFanTrayIndex}}"
    },
    {
     "expr": "dellNetPowerSupplyOperStatus{alias=\"$device\"}",
     "legendFormat": "{{__name__}} Chassis {{dellNetPowerDeviceIndex}} Index {{dellNetPowerSupplyIndex}}"
    }
   ]
  },
  {
   "title": "Resource Utilization %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(dellNetCpuUtil5Sec{alias=\"$device\"})",
     "legendFormat": "CPU "
    },
    {
     "expr": "dellNetCpuUtilMemUsage{alias=\"$device\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "dellNetCpuFlashUsage{alias=\"$device\"}",
     "legendFormat": "Flash"
    }
   ]
  }
 ]
}